kind: blog
title: "Observing Emissary Ingress with OpenTelemetry and Dash0"
publication: "Dash0 Blog"
date: 2025-09-30
url: "https://www.dash0.com/blog/observing-emissary-ingress-with-opentelemetry-and-dash0"
summary: "Emissary Ingress is more than just an ingress controller - it’s an API gateway built on Envoy. In this fourth installment of our series on ingress observability with OpenTelemetry, we show how to capture traces, metrics,"
image: "https://www.dash0.com/_content/blog/observing-emissary-ingress-with-opentelemetry-and-dash0/emissary-otel.png"
