name: "CKAD: Certified Kubernetes Application Developer"
issuer: "The Linux Foundation"
issued: 2023-04-13
url: "https://www.credly.com/users/kasper-nissen"
image: "./ckad-certified-kubernetes-application-developer-2023-04-13.png"
