name: "CKAD: Certified Kubernetes Application Developer"
issuer: "The Linux Foundation"
issued: 2023-04-13
url: "https://www.credly.com/badges/10f407d6-430a-44eb-a4fb-328ea515ead0/public_url"
image: "./ckad-certified-kubernetes-application-developer-2023-04-13.png"
