name: "PCA: Prometheus Certified Associate"
issuer: "The Linux Foundation"
issued: 2024-04-22
url: "https://www.credly.com/users/kasper-nissen"
image: "./pca-prometheus-certified-associate-2024-04-22.png"
