title: "Tech Talks: Prometheus - The Current State and the Road Ahead with Julius Volz (moderator)"
event: Cloud Native Nordics virtual event
date: 2020-06-10
youtube_id: bH78UXb1aVE
tags: []
featured: false
sources:
  github: tech-talks-prometheus-the-current-state-and-the-road-ahead-with-julius-volz-moderator-2020-06
  youtube: bH78UXb1aVE
